### ISSUE TITLE
[Bug] [V3] Option body

### ISSUE THREAD

**Issue by Revadike** [codemanki/cloudscraper#134]
Using passing Object as body option will result into this error:
```
Argument error, options.body.
_http_outgoing.js:607
    throw new ERR_INVALID_ARG_TYPE('first argument',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type object
    at write_ (_http_outgoing.js:607:11)
    at ClientRequest.write (_http_outgoing.js:579:10)
    at Request.write (C:\Users\Roy\AppData\Roaming\npm\node_modules\cloudscraper\node_modules\request\request.js:1500:27)
    at end (C:\Users\Roy\AppData\Roaming\npm\node_modules\cloudscraper\node_modules\request\request.js:549:18)
    at Immediate.<anonymous> (C:\Users\Roy\AppData\Roaming\npm\node_modules\cloudscraper\node_modules\request\request.js:578:7)
    at processImmediate (timers.js:637:19)
```

**Comment by codemanki** [comment]
@Revadike thanks for reporting! Could you please also share the code that causes this issue?

**Comment by Revadike** [comment]
Uh, sure.
```js
const CF = require(`cloudscraper`);

//...

         CF({
                url: `https://redacted.com/api/v2/users`,
                method: `POST`,
                json: true,
                body: {
                    "email": email
                },
            }, (error, response) => {
                if (error) {
                    Logger.error(error);
                    return;
                }
                //...
          });
```

**Comment by codemanki** [comment]
@Revadike `body` should now be `formData` as in request - https://github.com/request/request#multipartform-data-multipart-form-uploads

**Comment by pro-src** [comment]
Actually, thats valid usage, from request [options](https://github.com/request/request#requestoptions-callback):
> body - entity body for PATCH, POST and PUT requests. Must be a Buffer, String or ReadStream. If json is true, then body must be a JSON-serializable object.

**Comment by pro-src** [comment]
This indeed seems to be a problem with `request` and not cloudscraper. The same thing happens when using `request` directly.

```js
var request = require('request');
request.post({
  uri: 'https://jsonplaceholder.typicode.com/posts/1',
  type: 'json',
  body: { test: true }
}, console.log);
```
or
```js
var request = require('request-promise');
request.post({
  uri: 'https://jsonplaceholder.typicode.com/posts/1',
  type: 'json',
  body: { test: true }
}).then(body => console.log(body, '\n\nBody is ' + typeof body), console.error);
```

**Comment by pro-src** [comment]
@Revadike Alright, lol, I got thrown off by this issue but the deal here is that you must add  `json: true` if body is an object. This is not a problem with cloudscraper. Please open an issue about the documentation at https://github.com/request/request/issues

@codemanki Please close this issue.
