### ISSUE TITLE
Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by aalireza439** [codemanki/cloudscraper#15]
i try to get link is redirected.
 i get this errror : 

```javascript
/home/amy/node_modules/cloudscraper/index.js:177
    if(response.statusCode === 302) { //occurrs when posting. request is supposed to auto-follow these
               ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/home/amy/node_modules/cloudscraper/index.js:177:16)
    at self.callback (/home/amy/node_modules/request/request.js:200:22)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at Request.onRequestError (/home/amy/node_modules/request/request.js:826:8)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at emitErrorNT (net.js:1249:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by codemanki** [comment]
Please share the content of `error ` and `body` objects here. Thanks

**Comment by cagnulein** [comment]
I have the same issue but happens very rarely.

**Comment by codemanki** [comment]
@cagnulein could you share the error and body objects here next time you get into this issue?

**Comment by bato3** [comment]
```
error: { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 

response: undefined 

body: undefined
```

**Comment by codemanki** [comment]
@bato3 thanks. will look into this asap
