### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by bato3** [codemanki/cloudscraper#18]
When i'm using proxy for HTTPS requests after long time sometimes happen this:

```
node_modules/cloudscraper/index.js:201
    callback(error, response, body.toString(options.realEncoding));
                                  ^

TypeError: Cannot read property 'toString' of undefined
    at giveResults (node_modules/cloudscraper/index.js:201:35)
    at Request._callback (node_modules/cloudscraper/index.js:186:7)
    at self.callback (node_modules/request/request.js:200:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (node_modules/request/request.js:831:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:264:9)
    at emitOne (events.js:77:13)
```
```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
process.env.HTTP_PROXY = 'http://138.0.172.145:80'; //this proxy sometimes works..
```

**Comment by bato3** [comment]
it's this after some fixes: https://github.com/codemanki/cloudscraper/issues/15
