### ISSUE TITLE
Yet another Unexpected token (ParserError)

### ISSUE THREAD

**Issue by ThomasF34** [codemanki/cloudscraper#231]
Hi, i got a ParserError when i'm trying to use `get` method

  * What version of Cloudscraper are you using?
    - 4.1.2
  
  * What version of Node.js are you using? 
    - 10.15.3

```
Unhandled rejection ParserError: 
### Cloudflare may have changed their technique, or there may be a bug.
### Bug Reports: https://github.com/codemanki/cloudscraper/issues
### Check the detailed exception message that follows for the cause.

SyntaxError: Challenge evaluation failed: Unexpected token |
    at solveChallenge (node_modules/torrent-search-api/node_modules/cloudscraper/index.js:254:21)
    at Timeout._onTimeout (node_modules/torrent-search-api/node_modules/cloudscraper/index.js:179:7)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

Before the error was thrown, last lines of the debugger were : 

```
REQUEST end event my-link
REQUEST has body my-link 9270
REQUEST emitting complete my-link
```

Cloudflare changed their technique or am i using something wrongly ? 
Thank for your help 😄 

(I saw both #190 and #192 were close to the problem i have, but i wasn't able to find any solution there)

- [x] I have read the [README](https://github.com/codemanki/cloudscraper#readme). (Code [examples](https://github.com/codemanki/cloudscraper/tree/master/docs/examples#readme))

<details><summary>Code snippet</summary>

```js
cloudscraper.get("my-link")
        .then(
          res => console.log(res)
        );
```
</details>

**Comment by codemanki** [comment]
Thanks for reporting this. I will take a look asa

**Comment by pro-src** [comment]
I tried a couple of protected sites without issue. It's doubtful that we can resolve this issue without having a URL to reproduce the problem.

If I had to guess, the server is putting `cloudflare` somewhere in the HTTP response *server* header aka `Server: cloudflare` which makes the request ambiguous.

The Easiest way to tell what is going on is to catch the error and save the response.

```js
const cloudscraper = require('cloudscraper');
const fs = require('fs');

async function test(url, outFile) {
  try {
    const html = await cloudscraper.get(url);
    console.log(html);
  } catch(error) {
    console.log(error.message);
    fs.writeFileSync(outFile, error.response.body.toString('utf-8'), 'utf-8');
  }
}

test('https://pro-src.com', './out.html');
```

If the response is Cloudflare's HTML, share it and we'll fix it.

**Comment by pro-src** [comment]
@ThomasF34, if it's not CF's HTML, take a look at https://github.com/codemanki/cloudscraper/blob/master/docs/examples/ignore-error.js

**Comment by pro-src** [comment]
This can be reopened this if you're still having problems, just lmk.

**Comment by ThomasF34** [comment]
Hi !! Sorry i've been very busy and i had no time to work on my project. This evening i've been able to dig into this bug i had. 

This is the Cloudflare's HTML i have using your [test function](https://github.com/codemanki/cloudscraper/issues/231#issuecomment-508899863)

```
<!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <title>Just a moment...</title>
  <style type="text/css">
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; font-family: Helvetica, Arial, sans-serif; font-size: 100%;}
    h1 {font-size: 1.5em; color: #404040; text-align: center;}
    p {font-size: 1em; color: #404040; text-align: center; margin: 10px 0 0 0;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 20px;}
    @-webkit-keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0); } }
    @keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0); } }
    .bubbles { background-color: #404040; width:15px; height: 15px; margin:2px; border-radius:100%; -webkit-animation:bubbles 0.6s 0.07s infinite ease-in-out; animation:bubbles 0.6s 0.07s infinite ease-in-out; -webkit-animation-fill-mode:both; animation-fill-mode:both; display:inline-block; }
  </style>

    <script type="text/javascript">
  //<![CDATA[
  (function(){
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
    b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
    b(function(){
      var a = document.getElementById('cf-content');a.style.display = 'block';
      setTimeout(function(){
        var s,t,o,p,b,r,e,a,k,i,n,g,f, vIIeLxL={"SJy":+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(+!![]))/+((+!![]+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]))};
        g = String.fromCharCode;
        o = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
        e = function(s) {
          s += "==".slice(2 - (s.length & 3));
          var bm, r = "", r1, r2, i = 0;
          for (; i < s.length;) {
              bm = o.indexOf(s.charAt(i++)) << 18 | o.indexOf(s.charAt(i++)) << 12
                      | (r1 = o.indexOf(s.charAt(i++))) << 6 | (r2 = o.indexOf(s.charAt(i++)));
              r += r1 === 64 ? g(bm >> 16 & 255)
                      : r2 === 64 ? g(bm >> 16 & 255, bm >> 8 & 255)
                      : g(bm >> 16 & 255, bm >> 8 & 255, bm & 255);
          }
          return r;
        };
        t = document.createElement('div');
        t.innerHTML="<a href='/'>x</a>";
        t = t.firstChild.href;r = t.match(/https?:\/\//)[0];
        t = t.substr(r.length); t = t.substr(0,t.length-1); 
        a = document.getElementById('jschl-answer');
        f = document.getElementById('challenge-form');
        ;vIIeLxL.SJy+=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]))/+((!+[]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));vIIeLxL.SJy*=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(+!![]))/+((!+[]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]));vIIeLxL.SJy-=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]))/+((+!![]+[])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));vIIeLxL.SJy+=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(+!![]))/+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!![])+(!+[]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]));vIIeLxL.SJy-=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]))/+((!+[]+!![]+!![]+[])+(!+[]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));vIIeLxL.SJy+=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+!![]+[])+(+!![])+(+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]));a.value = (+vIIeLxL.SJy + t.length).toFixed(10); '; 121'
        f.action += location.hash;
        f.submit();
      }, 4000);
    }, false);
  })();
  //]]>
</script>


</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript><h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1></noscript>
  <div id="cf-content" style="display:none">
    
    <div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> itorrents.org.</h1>
    
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p>
  </div>
   
  <form id="challenge-form" action="/cdn-cgi/l/chk_jschl" method="get">
    <input type="hidden" name="s" value="a2ac15ab47268b07abb48768d80e659972468bc0-1564603293-1800-AbeJ6WU9rjCk0tXOdCFfWhGTbx3a/QZlL5aginbwNaEngYnAyu+qDHTs+AShSInxl16DV2wDHJKJ16xQKVHYzFCRj7cWH6PePPxAOUFVE6K/kevAwHrVfAkjbqEQzxgbcemYsBHCWl27tT6l21lZkY3cfNTDPg7XQ+Q5WrG6DAPCYj5JgF7hA2Nd2VRJ1iwYQg=="></input>
    <input type="hidden" name="jschl_vc" value="d858527cce7b7769ba8ca172280a640f"/>
    <input type="hidden" name="pass" value="1564603297.907-3wru++m0wG"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>
  
</div>

          
          <div class="attribution">
            <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=iuam" target="_blank" style="font-size: 12px;">DDoS protection by Cloudflare</a>
            <br>
            Ray ID: 4ff22a3ae823cdcb
          </div>
      </td>
     
    </tr>
  </table>
</body>
</html>
```

Do you have any idea how to fix this ? 
Thanks for you help, and again sorry for the delay :)

**Comment by pro-src** [comment]
Hey,

I've tested itorrents.org and the provided HTML using CloudScraper's test suite on Node.js v10.15.3. Everything is fine so I'm clueless as to what is causing this problem for you.

Double check your Node.js version though: `node -p process.versions`
And the version of Cloudscraper: `node -p 'require("cloudscraper/package").version'`

**Comment by ThomasF34** [comment]
Hi, 

That's weird. I tested again with link `http://itorrents.org/torrent/26968E916E7D5BDE409CB068DA657E87F0B12C6F.torrent` Is it working for you with this link ? 

About versioning here is my versions : 
```
$ node -p process.versions 
{ http_parser: '2.8.0',
  node: '10.15.3',
  v8: '6.8.275.32-node.51',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0j',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
```

```
$ node -p 'require("cloudscraper/package").version'
4.1.2
```

**Comment by pro-src** [comment]
@ThomasF34 Good and bad news :smile: 

It's not the link. I don't know how I missed this before but the stacktrace is a dead give away:

```
SyntaxError: Challenge evaluation failed: Unexpected token |
    at solveChallenge (node_modules/torrent-search-api/node_modules/cloudscraper/index.js:254:21)
```

The `solveChallenge` function doesn't exist in v4.1.2 and hasn't existed since support for reCAPTCHA solving was added prior to v4.0.0.

You can see the change in this commit: https://github.com/codemanki/cloudscraper/commit/14eb38190cacdf0205293b3ddb785f28e3ac2313

So it's conclusive that you're using v3.9.1 or earlier. You'll have to troubleshoot your NPM + Node.js installation to fix this.

Cheers

**Comment by pro-src** [comment]
Maybe this will help:
```js
const cloudscraper = require('cloudscraper');
const version = require('cloudscraper/package').version;

if (version !== '4.1.2') {
  console.log('Unexpected CloudScraper version:', version);
  console.log('CloudScraper was loaded from:', require.resolve('cloudscraper'));
  process.exit(1);
}

const uri = 'http://itorrents.org/torrent/26968E916E7D5BDE409CB068DA657E87F0B12C6F.torrent';
cloudscraper.get({ encoding: null, uri })
  .then(bin => fs.writeFileSync('./torrent', bin, 'utf-8'));
```
