### ISSUE TITLE
CaptchaError

### ISSUE THREAD

**Issue by zaoqi** [codemanki/cloudscraper#251]
_Please attempt to answer the following questions before submitting a new issue:_

  * What version of Cloudscraper are you using?
    - `node -p 'require("cloudscraper/package.json").version'`
  * What version of Node.js are you using? (Please share the process information)
    - `node -p process`
  * When did the problem start occurring?
  * How often does the problem occur?
  * What is the URL?
  * Are there any similar issues? (Please share the links)

- [ ] I have read the [README](https://github.com/codemanki/cloudscraper#readme). (Code [examples](https://github.com/codemanki/cloudscraper/tree/master/docs/examples#readme))

_Please share a minimal working code snippet that reproduces the problem._
<details><summary>Code snippet</summary>

```js
INSERT CODE HERE
```
</details>

```
{ CaptchaError: captcha
    at validateResponse (/usr/local/bin/node_modules/cloudscraper/index.js:232:11)
    at onCloudflareResponse (/usr/local/bin/node_modules/cloudscraper/index.js:195:5)
    at onRequestResponse (/usr/local/bin/node_modules/cloudscraper/index.js:178:5)
    at Request.<anonymous> (/usr/local/bin/node_modules/cloudscraper/index.js:137:7)
    at Object.onceWrapper (events.js:286:20)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/local/bin/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Gunzip.<anonymous> (/usr/local/bin/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at Gunzip.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) name: 'CaptchaError', message: 'captcha' }
```

**Comment by pro-src** [comment]
Hi @zaoqi,

The stacktrace shows what may be a perfectly valid error for the site/page being scraped. If the CAPTCHA doesn't occur in the web browser, troubleshooting would be appropriate. However, we can't troubleshoot anything with the information you've provided. Did you read the README, did you read the issue template?

If there is an legitmate issue, please open a new thread with the revelant information so we can assist you. I'm closing this issue as it is currently invalid.

Cheers
