### ISSUE TITLE
ParserError

### ISSUE THREAD

**Issue by FastPure** [codemanki/cloudscraper#257]
_Please attempt to answer the following questions before submitting a new issue:_

  * What version of Cloudscraper are you using?
    - Im using the latest one availible in npm.
  * What version of Node.js are you using? (Please share the process information)
    - >10
  * When did the problem start occurring?
     -> After implementing
  * How often does the problem occur?
     -> All the time
  * What is the URL?
https://backpack.tf/api/classifieds/search/v1

  * Are there any similar issues? (Please share the links)
https://github.com/codemanki/cloudscraper/issues/192

- [ ] I have read the [README](https://github.com/codemanki/cloudscraper#readme). (Code [examples](https://github.com/codemanki/cloudscraper/tree/master/docs/examples#readme))

_Please share a minimal working code snippet that reproduces the problem._
<details><summary>Code snippet</summary>

```js
(node:11636) UnhandledPromiseRejectionWarning: ParserError:
### Cloudflare may have changed their technique, or there may be a bug.
### Bug Reports: https://github.com/codemanki/cloudscraper/issues
### Check the detailed exception message that follows for the cause.

challengeId (jschl_vc) extraction failed
    at onChallenge (C:\Users\Pichau\Desktop\Connectivity\node_modules\cloudscraper\index.js:274:21)
    at onCloudflareResponse (C:\Users\Pichau\Desktop\Connectivity\node_modules\cloudscraper\index.js:220:12)
    at onRequestResponse (C:\Users\Pichau\Desktop\Connectivity\node_modules\cloudscraper\index.js:178:5)
    at Request.<anonymous> (C:\Users\Pichau\Desktop\Connectivity\node_modules\cloudscraper\index.js:137:7)
    at Object.onceWrapper (events.js:273:13)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\Users\Pichau\Desktop\Connectivity\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\Users\Pichau\Desktop\Connectivity\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at module.exports.runLoopOnce (C:\Users\Pichau\Desktop\Connectivity\node_modules\deasync\index.js:64:10)
    at module.exports (C:\Users\Pichau\Desktop\Connectivity\node_modules\deasync-promise\index.js:13:9)
    at Object.module.exports.interval [as Get_Sleep] (C:\Users\Pichau\Desktop\Connectivity\node_modules\system-sleep\module.js:24:36)
    at Fn_Make_Request.Promise (C:\Users\Pichau\Desktop\Connectivity\bptf_get_classifieds.js:87:17)
    at new Promise (<anonymous>)
    at Fn_Make_Request (C:\Users\Pichau\Desktop\Connectivity\bptf_get_classifieds.js:5:12)
    at Fn_Get_Classifieds.Promise (C:\Users\Pichau\Desktop\Connectivity\bptf_get_classifieds.js:302:17)
    at new Promise (<anonymous>)
    at Object.Fn_Get_Classifieds [as Get_Classifieds] (C:\Users\Pichau\Desktop\Connectivity\bptf_get_classifieds.js:223:12)
(node:11636) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
</details>

**Comment by pro-src** [comment]
Hi @FastPure,

Would you please share the output of the following example: https://github.com/codemanki/cloudscraper/blob/master/docs/examples/debugging.js?

```sh
git clone https://github.com/codemanki/cloudscraper
cd cloudcraper && npm install
node docs/examples/debugging.js "https://backpack.tf/api/classifieds/search/v1"
```

Two files should be created: `request.json` and `headers.json`
If there is an error, an additional file will be created: `error.txt`

You could upload them to https://dpaste.com or some other pastebin site.
If you're getting a 403, please share the response body e.g. `node docs/examples/debugging.js "https://backpack.tf/api/classifieds/search/v1"`
If you're getting a parser error, please modify one of the examples to show/save the response body: `error.response.body.toString('utf8')`.

If you modify the example in any other way, please inform and share a code snippet.

**Comment by pro-src** [comment]
Hi @FastPure,

I need more information to troubleshoot this issue, please follow these instructions.

Share the output of the following example: https://github.com/codemanki/cloudscraper/blob/master/docs/examples/debugging.js?

```sh
git clone https://github.com/codemanki/cloudscraper
cd cloudcraper && npm install
node docs/examples/debugging.js "https://backpack.tf/api/classifieds/search/v1"
```

Two files should be created: `request.json` and `headers.json`
If there is an error, an additional file will be created: `error.txt`

Upload them to https://dpaste.com or some other pastebin site and share the link.
If you're getting a 403, share the response body e.g. `node docs/examples/captcha-html.js "https://backpack.tf/api/classifieds/search/v1"`
If you're getting a parser error, modify one of the examples to show/save the response body: `error.response.body.toString('utf8')`.

If you modify the example in any other way, share a code snippet.

Cheers

**Comment by pro-src** [comment]
@FastPure
