### ISSUE TITLE
Issue solving recaptcha since yesterday

### ISSUE THREAD

**Issue by prototypesecurity** [codemanki/cloudscraper#281]
FIXED

**Comment by 8bit-echo** [comment]
Same here.  My stack trace is showing a captcha issue:
`{ CaptchaError: captcha
    at validateResponse (.../node_modules/cloudscraper/index.js:259:11)
    at onCloudflareResponse (.../node_modules/cloudscraper/index.js:222:5)
    at onRequestResponse (.../node_modules/cloudscraper/index.js:205:5)
    at Request.<anonymous> (.../node_modules/cloudscraper/index.js:149:7)
    at Object.onceWrapper (events.js:286:20)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (.../node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (.../node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) name: 'CaptchaError', message: 'captcha' }`

I think cloudfare must have changed their captcha implementation.

**Comment by 8bit-echo** [comment]
I solved this issue by running `yarn add brotli@1.3.2` in my project.

**Comment by prototypesecurity** [comment]
@8bit-echo how can i fix it on debian? please help me i cant still solve recaptcha!
