### ISSUE TITLE
Captcha Error when no Captcha exists

### ISSUE THREAD

**Issue by GlitchSabre** [codemanki/cloudscraper#301]
I keep getting captcha error when trying to request https://4anime.to/recently-added . It seems there is no actual captcha test when trying to access the website. There is only CloudFlare's DDoS protection. II have tried with other scraping packages and they seem to only encounter Cloudflare's DDoS 5 second wait test.

Node: v12.13.0
Error generated:
`............................................
name: 'CaptchaError',
  message: 'captcha'
}`

My code: 
`const cf = require('cloudscraper')
cf.get("https://4anime.to/recently-added") .then(console.log,console.error)`
`
Other modules(that may interfere):
- cheerio
- request

**Comment by codemanki** [comment]
Just checked your url, works fine for me.If you keep getting the recaptcha error then please post the response.body here so I could investigate it. But normally recaptcha is detected by recaptcha key words in the body, so there should be no errors

**Comment by GlitchSabre** [comment]
The error I am getting:

`{ CaptchaError: captcha
    at validateResponse (/home/gl1tch/Desktop/projects/scrape/node_modules/cloudscraper/index.js:273:11)
    at onCloudflareResponse (/home/gl1tch/Desktop/projects/scrape/node_modules/cloudscraper/index.js:222:5)
    at onRequestResponse (/home/gl1tch/Desktop/projects/scrape/node_modules/cloudscraper/index.js:205:5)
    at Request.<anonymous> (/home/gl1tch/Desktop/projects/scrape/node_modules/cloudscraper/index.js:149:7)
    at Object.onceWrapper (events.js:286:20)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/gl1tch/Desktop/projects/scrape/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Gunzip.<anonymous> (/home/gl1tch/Desktop/projects/scrape/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at Gunzip.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) name: 'CaptchaError', message: 'captcha' }`
