### ISSUE TITLE
Request fails on first call, works on all subsequent calls.

### ISSUE THREAD

**Issue by dscalzi** [codemanki/cloudscraper#313]
Cloudscrapper fails on the first request to dev bukkit links. All subsequent requests work. Error on first request:

```
Unhandled rejection CaptchaError: captcha
    at validateResponse (d:\Development\Node.js\PluginBadges\node_modules\cloudscraper\index.js:273:11)
    at onCloudflareResponse (d:\Development\Node.js\PluginBadges\node_modules\cloudscraper\index.js:222:5)
    at onRequestResponse (d:\Development\Node.js\PluginBadges\node_modules\cloudscraper\index.js:205:5)
    at Request.<anonymous> (d:\Development\Node.js\PluginBadges\node_modules\cloudscraper\index.js:149:7)
    at Object.onceWrapper (events.js:300:26)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (d:\Development\Node.js\PluginBadges\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:210:5)
    at Gunzip.<anonymous> (d:\Development\Node.js\PluginBadges\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at Gunzip.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

  * What version of Cloudscraper are you using?
    - `4.5.0` (latest)
  * What version of Node.js are you using? (Please share the process information)
    - `12.13.0`
  * When did the problem start occurring?
    - Unknown
  * How often does the problem occur?
    - On the first request, all subsequent requests work.
  * What is the URL?
    - DevBukkit links ex. `https://dev.bukkit.org/projects/skychanger/`
  * Are there any similar issues? (Please share the links)
    - Unknown

- [x] I have read the [README](https://github.com/codemanki/cloudscraper#readme). (Code [examples](https://github.com/codemanki/cloudscraper/tree/master/docs/examples#readme))

_Please share a minimal working code snippet that reproduces the problem._
<details><summary>Code snippet</summary>

Just a simple get call, nothing fancy.
https://github.com/dscalzi/PluginBadges/blob/master/index.js#L69

```js
cloudscraper.get(url, (err, resp, body) => {
    if(err){
        console.error(`Cloudflare Request error for ${url}. Not caching result..`, err)
        resolve(-1)
    } else {
        resolve(_doParse(body, regex))
    }
})
```
</details>

**Comment by codemanki** [comment]
Should be fixed in `4.6.0`. Please update and try again
