### ISSUE TITLE
 CloudflareError: Cloudflare challenge loop

### ISSUE THREAD

**Issue by tsao-chi** [codemanki/cloudscraper#323]
_Please attempt to answer the following questions before submitting a new issue:_

  * What version of Cloudscraper are you using?
    - 4.5.0
  * What version of Node.js are you using? (Please share the process information)
    - v13.7.0
  * When did the problem start occurring? 22 hours ago
  * How often does the problem occur? every time
  * What is the URL? `https://www.spigotmc.org/resources/vault.34315/download?version=271004` `https://www.spigotmc.org/resources/lightapi-fork.48247/download?version=305658` etc
  * Are there any similar issues? (Please share the links)

- [x] I have read the [README](https://github.com/codemanki/cloudscraper#readme). (Code [examples](https://github.com/codemanki/cloudscraper/tree/master/docs/examples#readme))

_Please share a minimal working code snippet that reproduces the problem._
<details><summary>Code snippet</summary>

```js
const request = require('cloudscraper')
const fs = require('fs')
const util = require('util')
const writeFile = util.promisify(fs.writeFile)
async function download(path, url){
  try {
    console.log(`Downloading ${url} to ${path} ...`)
    const result = await request({
      method: 'GET',
      encoding: null,
      url: url,
    })
    await writeFile(path, result, 'binary')
  } catch(e) {
    console.log(`Download failed: ${url}  error=${e}`)
    throw e}}
// download(<somewhere>, <url>)
```
</details>

**Comment by RedNinjaX** [comment]
Same issue here. Similar setup

**Comment by fail2ban1337** [comment]
I have the sam problem .

**Comment by sevikon** [comment]
Same issue here. Cloudflare challenge loop.

**Comment by ChrisMichaelPerezSantiago** [comment]
Same issue!

```shell
CloudflareError: Cloudflare challenge loop
```

**Comment by happyday517** [comment]
Same issue!

**Comment by RickDB** [comment]
Same here.

**Comment by codemanki** [comment]
Should be fixed in `4.6.0`. Please update and try again

**Comment by RedNinjaX** [comment]
Can confirm its working 👌Apologies for any stern feelings

**Comment by ChrisMichaelPerezSantiago** [comment]
Hi @RedNinjaX ,

After updating the library and having done a test of my api with travis, I kept showing the error:

```shell
CloudflareError: Cloudflare challenge loop
    at onChallenge (/home/travis/build/ChrisMichaelPerezSantiago/animeflv/node_modules/cloudscraper/index.js:298:13)
    at onCloudflareResponse (/home/travis/build/ChrisMichaelPerezSantiago/animeflv/node_modules/cloudscraper/index.js:235:12)
    at onRequestResponse (/home/travis/build/ChrisMichaelPerezSantiago/animeflv/node_modules/cloudscraper/index.js:205:5)
    at Request.<anonymous> (/home/travis/build/ChrisMichaelPerezSantiago/animeflv/node_modules/cloudscraper/index.js:149:7)
    at Object.onceWrapper (events.js:428:26)
    at Request.emit (events.js:321:20)
    at Request.<anonymous> (/home/travis/build/ChrisMichaelPerezSantiago/animeflv/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:321:20)
    at IncomingMessage.<anonymous> (/home/travis/build/ChrisMichaelPerezSantiago/animeflv/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:427:28)
    at IncomingMessage.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'CloudflareError',
  message: 'Cloudflare challenge loop',
  errorType: 4
}
```

**Comment by codemanki** [comment]
@ChrisMichaelPerezSantiago which URI are you trying to access with cloudscraper?

**Comment by ChrisMichaelPerezSantiago** [comment]
This one
https://m.animeflv.net/
