### ISSUE TITLE
ParserError on opening any cloudflare website

### ISSUE THREAD

**Issue by Bassintag** [codemanki/cloudscraper#325]
using version: __4.5.0__

The bug started occuring yesterday, it has become impossible to scrap any page that uses cloudflare and that produces a challenge.

Here is the exception:

```
Challenge form extraction failed
    at onCaptcha
    at onCloudflareResponse (...\cloudscraper\index.js:226:14)
    at onRequestResponse (...\cloudscraper\index.js:205:5)
    at Request.<anonymous> (...\cloudscraper\index.js:149:7)
    at Object.onceWrapper (events.js:288:20)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (...\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at Gunzip.<anonymous> (...\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at Gunzip.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  name: 'ParserError',
  message: '\n### Cloudflare may have changed their technique, or there may ' +
    'be a bug.\r' +
    '\n### Bug Reports: ' +
    'https://github.com/codemanki/cloudscraper/issues\r' +
    '\n### Check the detailed exception message that follows for the ' +
    'cause.\r' +
    '\n\r' +
    '\nChallenge form extraction failed'
}
```

Here's the url used (works on any cloudflare url): https://stress95.com/en/auth/view?op=register

**Comment by codemanki** [comment]
Should be fixed in `4.6.0`. Please update and try again
