### ISSUE TITLE
CloudflareError: Cloudflare challenge loop error in latest version

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [codemanki/cloudscraper#327]
_Please attempt to answer the following questions before submitting a new issue:_

  * What version of Cloudscraper are you using?
    - v4.6.0
  * What version of Node.js are you using? (Please share the process information)
```javascript
  process {
    version: 'v12.13.1',
    versions: {
       node: '12.13.1',
       v8: '7.7.299.13-node.16'
     },
     // .....
  }
 ```

  * When did the problem start occurring?
    - The problem started to come up again after updating the cloudscraper lib to v.4.6.0
  
 * How often does the problem occur?
    -  The error is always shown once I performed a test with travis.
 
 * What is the URL?
    - https://animeflv.net/
  
* Are there any similar issues? (Please share the links)
    - Problem similar to #323 
- [x] I have read the [README](https://github.com/codemanki/cloudscraper#readme). (Code [examples](https://github.com/codemanki/cloudscraper/tree/master/docs/examples#readme))

## Error
```shell
CloudflareError: Cloudflare challenge loop
    at onChallenge (/home/travis/build/ChrisMichaelPerezSantiago/animeflv/node_modules/cloudscraper/index.js:298:13)
    at onCloudflareResponse (/home/travis/build/ChrisMichaelPerezSantiago/animeflv/node_modules/cloudscraper/index.js:235:12)
    at onRequestResponse (/home/travis/build/ChrisMichaelPerezSantiago/animeflv/node_modules/cloudscraper/index.js:205:5)
    at Request.<anonymous> (/home/travis/build/ChrisMichaelPerezSantiago/animeflv/node_modules/cloudscraper/index.js:149:7)
    at Object.onceWrapper (events.js:428:26)
    at Request.emit (events.js:321:20)
    at Request.<anonymous> (/home/travis/build/ChrisMichaelPerezSantiago/animeflv/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:321:20)
    at IncomingMessage.<anonymous> (/home/travis/build/ChrisMichaelPerezSantiago/animeflv/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:427:28)
    at IncomingMessage.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'CloudflareError',
  message: 'Cloudflare challenge loop',
  errorType: 4
}
```

**Comment by JuanM04** [comment]
I also made an API for AnimeFLV with GraphQL and the same is happening

**Comment by Bassintag** [comment]
Also having a similar issue with https://stress95.com/
A captcha challenge is automatically returned when using cloudscraper but not manually.
Not sure if it is for the same reason or not.

**Comment by GwenBFX** [comment]
I have a similar issue on https://www.slamjam.com/ when trying to send POST requests. Sometimes it succeed after many retries and having rotate proxies
