### ISSUE TITLE
setTimeout callback extraction failed

### ISSUE THREAD

**Issue by TheAleNet** [codemanki/cloudscraper#341]
When I try to run my script it gives me this error:

```
setTimeout callback extraction failed
    at onChallenge (/root/node_modules/cloudscraper/index.js:333:21)
    at onCloudflareResponse (/root/node_modules/cloudscraper/index.js:247:12)
    at onRequestResponse (/root/node_modules/cloudscraper/index.js:205:5)
    at Request.<anonymous> (/root/node_modules/cloudscraper/index.js:149:7)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/root/node_modules/request/request.js:1154:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/root/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'ParserError',
  message: '\n### Cloudflare may have changed their technique, or there may be a bug.\n### Bug Reports: https://github.com/codemanki/cloudscraper/issues\n### Check the detailed exception message that follows for the cause.\n\nsetTimeout callback extraction failed' }
```
I currently have the 4.5.0 version of cloudscraper and 8.10.0 of node.

**Comment by conpatto** [comment]
^

**Comment by MrReacher** [comment]
same issue here

**Comment by Zirpoo** [comment]
index.js line 330
the **match** method is wrong.

It worked by doing **exec** instead.

`regex.exec(body)`

**Comment by Zirpoo** [comment]
Most likely the same error as in #185
